module.exports = [
  { name: 'auth', description: 'Методы авторизации' },
  { name: 'user', description: 'Профиль пользователя' },
  { name: 'address', description: 'Подсказки по адресам' },
  { name: 'news', description: 'Новости и метрика' },
  { name: 'residentProfiles', description: 'Лицевые счета пользователя' },
  { name: 'geolocation', description: 'Методы для работы с геолокацией' },
  { name: 'notifications', description: 'Методы для работы с уведомлениями' },
  { name: 'eds', description: 'Методы для работы с API системы ЕДС' },
  { name: 'edsServices', description: 'Методы для работы с API системы ЕДС Услуги' },
  { name: 'appointments', description: 'Запись на прием к директору УК' },
  { name: 'appeals', description: 'Обращение в УК' },
  { name: 'polls', description: 'Опросы' },
  { name: 'giszhkh', description: 'Данные портала Реформа ЖКХ (ГИС ЖКХ)' },
  { name: 'vacancies', description: 'Вакансии' },
  { name: 'loyalty', description: 'Программа лояльности' },
  { name: 'loyalty-private', description: 'Программа лояльности' },
  { name: 'loyalty-external', description: 'Программа лояльности' },
  { name: 'serviceMethods', description: 'Служебные методы' },
];
