module.exports = {
  BAD_REQUEST: {
    description: 'Bad request',
    status: 400,
    code: 'BAD_REQUEST_ERROR',
    descriptionRu: 'Неудачный запрос',
  },
  BAD_RESIDENT_ID: {
    description: 'Bad resident id',
    status: 400,
    code: 'BAD_RESIDENT_ID_ERROR',
    descriptionRu: 'Некорректный идентификатор резидента',
  },
  INCORRECT_RESIDENT_ID_PAYMENT_RECEIPT: {
    description: 'Incorrect payment value on the receipt',
    status: 400,
    code: 'INCORRECT_RESIDENT_ID_PAYMENT_RECEIPT',
    descriptionRu: 'Неверная сумма платежа в квитанции',
  },
  EMPTY_BODY: {
    description: 'Empty body is not allowed. Please fill the body',
    status: 400,
    code: 'EMPTY_BODY_ERROR',
    descriptionRu: 'Пустое тело запроса не допускается. Пожалуйста, заполните тело.',
  },
  VALIDATION: {
    description: 'Invalid request',
    status: 400,
    code: 'VALIDATION_ERROR',
    descriptionRu: 'Неверный запрос',
  },
  INVALID_REFRESH_SESSION: {
    description: 'Invalid session. Wrong fingerprint',
    status: 401,
    code: 'INVALID_REFRESH_SESSION_ERROR',
    descriptionRu: 'Недопустимый сеанс. Неправильный отпечаток.',
  },
  TOKEN_VERIFY: {
    description: 'Token verify error',
    status: 401,
    code: 'TOKEN_VERIFY_ERROR',
    descriptionRu: 'Ошибка верификации токена',
  },
  TOKEN_SIGNED: {
    description: 'Token signed error',
    status: 401,
    code: 'TOKEN_SIGNED_ERROR',
    descriptionRu: 'Ошибка подписи токена',
  },
  BAD_TOKEN: {
    description: 'Bad token',
    status: 401,
    code: 'BAD_TOKEN_ERROR',
    descriptionRu: 'Некорректный токен',
  },
  BAD_REFRESH_TOKEN: {
    description: 'Bad Refresh token',
    status: 401,
    code: 'BAD_REFRESH_TOKEN_ERROR',
    descriptionRu: 'Некорректный токен обновления',
  },
  WRONG_RESET_PASSWORD_TOKEN: {
    description: 'Reset password token is not registered. Probably it already used',
    status: 401,
    code: 'WRONG_RESET_PASSWORD_TOKEN_ERROR',
    descriptionRu: 'Токен сброса пароля не зарегистрирован. Вероятно, он уже использовался',
  },
  WRONG_SMS_CONFIRM_TOKEN: {
    description: 'Confirm sms token is not registered. Probably it already used',
    status: 401,
    code: 'WRONG_SMS_CONFIRM_TOKEN_ERROR',
    descriptionRu: 'SMS-токен подтверждения не зарегистрирован. Вероятно, он уже использовался',
  },
  WRONG_EMAIL_CONFIRM_TOKEN: {
    description: 'Confirm email token is not registered. Probably it already used',
    status: 401,
    code: 'WRONG_EMAIL_CONFIRM_TOKEN_ERROR',
    descriptionRu: 'E-mail токен подтверждения не зарегистрирован. Вероятно, он уже использовался',
  },
  PARSE_TOKEN: {
    description: 'Trying get data from access token. Something wrong',
    status: 401,
    code: 'PARSE_TOKEN_ERROR',
    descriptionRu: 'Ошибка получения данных из токена',
  },
  INVALID_SESSION: {
    description: 'Invalid session. Wrong fingerprint',
    status: 401,
    code: 'INVALID_SESSION_ERROR',
    descriptionRu: 'Недопустимый сеанс. Неправильный отпечаток',
  },
  UNAUTHORIZED: {
    description: 'Unauthorized',
    status: 401,
    code: 'UNAUTHORIZED_ERROR',
    descriptionRu: 'Для доступа к запрашиваемому ресурсу требуется аутентификация',
  },
  PAYMENT_REQUIRED: {
    description: 'Payment Required',
    status: 402,
    code: 'PAYMENT_REQUIRED_ERROR',
    descriptionRu: 'Требуется оплата',
  },
  FORBIDDEN: {
    description: 'Access forbidden',
    status: 403,
    code: 'FORBIDDEN_ERROR',
    descriptionRu: 'Доступ запрещен',
  },
  NO_ANONYMOUS_ACCESS: {
    description: 'Access denied. No anonymous access',
    status: 403,
    code: 'NO_ANONYMOUS_ACCESS_ERROR',
    descriptionRu: 'Доступ запрещен. Нет анонимного доступа',
  },
  BAD_ROLE: {
    description: 'Bad role',
    status: 403,
    code: 'BAD_ROLE_ERROR',
    descriptionRu: 'Неверная роль',
  },
  INVALID_CREDENTIALS: {
    description: 'Invalid credentials',
    status: 401,
    code: 'INVALID_CREDENTIALS_ERROR',
    descriptionRu: 'Неверные учетные данные',
  },
  INVALID_PASSWORD: {
    description: 'Invalid password',
    status: 401,
    code: 'INVALID_PASSWORD_ERROR',
    descriptionRu: 'Неверный пароль',
  },
  ACCESS: {
    description: 'Access denied',
    status: 403,
    code: 'ACCESS_ERROR',
    descriptionRu: 'Доступ запрещен',
  },
  ROUTE_NOT_FOUND: {
    description: 'Route not found',
    status: 404,
    code: 'ROUTE_NOT_FOUND_ERROR',
    descriptionRu: 'Маршрут не найден',
  },
  NOT_FOUND: {
    description: 'Empty response, not found',
    status: 404,
    code: 'NOT_FOUND_ERROR',
    descriptionRu: 'Пустой ответ, не найден',
  },
  METHOD_NOT_ALLOWED: {
    description: 'Method Not Allowed',
    status: 405,
    code: 'METHOD_NOT_ALLOWED_ERROR',
    descriptionRu: 'Указанный клиентом метод нельзя применить к текущему ресурсу',
  },
  NOT_ACCEPTABLE: {
    description: 'Not Acceptable',
    status: 406,
    code: 'NOT_ACCEPTABLE_ERROR',
    descriptionRu: 'Запрошенный URI не может удовлетворить переданным в заголовке характеристикам',
  },
  PROXY_AUTHENTICATION_REQUIRED: {
    description: 'Proxy Authentication Required',
    status: 407,
    code: 'PROXY_AUTHENTICATION_REQUIRED_ERROR',
    descriptionRu: 'Требуется проверка подлинности прокси-сервера',
  },
  REQUEST_TIMEOUT: {
    description: 'Request Timeout',
    status: 408,
    code: 'REQUEST_TIMEOUT_ERROR',
    descriptionRu: 'Время ожидания сервером передачи от клиента истекло',
  },
  EMAIL_ALREADY_TAKEN: {
    description: 'This email already taken, try use another',
    status: 409,
    code: 'EMAIL_ALREADY_TAKEN_ERROR',
    descriptionRu: 'Этот e-mail уже занят, попробуйте использовать другой',
  },
  PHONE_ALREADY_TAKEN: {
    description: 'This phone already taken, try use another',
    status: 409,
    code: 'PHONE_ALREADY_TAKEN_ERROR',
    descriptionRu: 'Этот телефон уже занят, попробуйте использовать другой',
  },
  DB_DUPLICATE_CONFLICT: {
    description: 'Duplicate conflict. Resource already exists',
    status: 409,
    code: 'DB_DUPLICATE_CONFLICT_ERROR',
    descriptionRu: 'Повторяющийся конфликт. Ресурс уже существует',
  },
  DUPLICATE_CONFLICT: {
    description: 'Duplicate conflict. Resource already exists',
    status: 409,
    code: 'DUPLICATE_CONFLICT_ERROR',
    descriptionRu: 'Повторяющийся конфликт. Ресурс уже существует',
  },
  CONFLICT: {
    description: 'Conflict',
    status: 409,
    code: 'CONFLICT_ERROR',
    descriptionRu: 'Запрос не может быть выполнен из-за конфликтного обращения к ресурсу',
  },
  GONE: {
    description: 'Gone',
    status: 410,
    code: 'GONE_ERROR',
    descriptionRu: 'Ресурс раньше был по указанному URL, но был удалён и теперь недоступен',
  },
  LENGTH_REQUIRED: {
    description: 'Length Required',
    status: 411,
    code: 'LENGTH_REQUIRED_ERROR',
    descriptionRu: 'Для указанного ресурса клиент должен указать Content-Length в заголовке запроса',
  },
  PRECONDITION_FAILED: {
    description: 'Precondition Failed',
    status: 412,
    code: 'PRECONDITION_FAILED_ERROR',
    descriptionRu: 'Предварительное условие не выполнено',
  },
  PAYLOAD_TOO_LARGE: {
    description: 'Payload Too Large',
    status: 413,
    code: 'PAYLOAD_TOO_LARGE_ERROR',
    descriptionRu: 'Слишком большая полезная нагрузка',
  },
  URI_TOO_LONG: {
    description: 'URI Too Long',
    status: 414,
    code: 'URI_TOO_LONG_ERROR',
    descriptionRu: 'URI слишком длинный',
  },
  UNSUPPORTED_MEDIA_TYPE: {
    description: 'Unsupported Media Type',
    status: 415,
    code: 'UNSUPPORTED_MEDIA_TYPE_ERROR',
    descriptionRu: 'Неподдерживаемый тип данных',
  },
  RANGE_NOT_SATISFIABLE: {
    description: 'Range Not Satisfiable',
    status: 416,
    code: 'RANGE_NOT_SATISFIABLE_ERROR',
    descriptionRu: 'В поле Range заголовка запроса был указан диапазон за пределами ресурса',
  },
  EXPECTATION_FAILED: {
    description: 'Expectation Failed',
    status: 417,
    code: 'EXPECTATION_FAILED_ERROR',
    descriptionRu: 'Сервер не может удовлетворить значению поля Expect заголовка запроса',
  },
  ALERT: {
    description: undefined,
    status: 418,
    code: 'ALERT_ERROR',
    descriptionRu: undefined,
  },
  TOKEN_EXPIRED: {
    description: 'Token expired',
    status: 419,
    code: 'TOKEN_EXPIRED_ERROR',
    descriptionRu: 'Срок действия токена истек',
  },
  SESSION_EXPIRED: {
    description: 'Session(refresh token) expired',
    status: 419,
    code: 'SESSION_EXPIRED_ERROR',
    descriptionRu: 'Сеанс (токен обновления) истек',
  },
  MISDIRECTED_REQUEST: {
    description: 'Misdirected Request',
    status: 421,
    code: 'MISDIRECTED_REQUEST_ERROR',
    descriptionRu: 'Неверно направленный запрос',
  },
  UNPROCESSABLE_ENTITY: {
    description: 'Unprocessable entity',
    status: 422,
    code: 'UNPROCESSABLE_ENTITY_ERROR',
    descriptionRu: 'Необработанный объект',
  },
  LOCKED: {
    description: 'Locked',
    status: 423,
    code: 'LOCKED_ERROR',
    descriptionRu: 'Заблокирован',
  },
  FAILED_DEPENDENCY: {
    description: 'Failed Dependency',
    status: 424,
    code: 'FAILED_DEPENDENCY_ERROR',
    descriptionRu: 'Неудачная зависимость',
  },
  TOO_EARLY: {
    description: 'Too Early',
    status: 425,
    code: 'TOO_EARLY_ERROR',
    descriptionRu: 'Слишком рано',
  },
  UPGRADE_REQUIRED: {
    description: 'Upgrade Required',
    status: 426,
    code: 'UPGRADE_REQUIRED_ERROR',
    descriptionRu: 'Требуется обновление',
  },
  PRECONDITION_REQUIRED: {
    description: 'Precondition Required',
    status: 428,
    code: 'PRECONDITION_REQUIRED_ERROR',
    descriptionRu: 'Требуется предварительное условие',
  },
  TOO_MANY_REQUESTS: {
    description: 'Too Many Requests',
    status: 429,
    code: 'TOO_MANY_REQUESTS_ERROR',
    descriptionRu: 'Слишком много запросов',
  },
  REQUEST_HEADER_FIELDS_TOO_LARGE: {
    description: 'Request Header Fields Too Large',
    status: 431,
    code: 'REQUEST_HEADER_FIELDS_TOO_LARGE_ERROR',
    descriptionRu: 'Слишком большие поля заголовка запроса',
  },
  UNAVAILABLE_FOR_LEGAL_REASONS: {
    description: 'Unavailable For Legal Reasons',
    status: 451,
    code: 'UNAVAILABLE_FOR_LEGAL_REASONS_ERROR',
    descriptionRu: 'Недоступен по юридическим причинам',
  },
  SERVER: {
    description: 'Server error occurred',
    status: 500,
    code: 'SERVER_ERROR',
    descriptionRu: 'Произошла ошибка сервера',
  },
  EXTERNAL: {
    description: 'External service error',
    status: 400,
    code: 'EXTERNAL_ERROR',
    descriptionRu: 'Ошибка внешнего сервиса',
  },
  DEV_IMPLEMENTATION: {
    description: 'Development implementation error',
    status: 500,
    code: 'DEV_IMPLEMENTATION_ERROR',
    descriptionRu: 'Ошибка реализации разработки',
  },
  NO_ARGUMENT: {
    description: 'Required arguments not supplied',
    status: 500,
    code: 'NO_ARGUMENT_ERROR',
    descriptionRu: 'Требуемые аргументы не указаны',
  },
  ARGUMENT_TYPE: {
    description: 'Wrong argument type',
    status: 500,
    code: 'ARGUMENT_TYPE_ERROR',
    descriptionRu: 'Неправильный тип аргумента',
  },
  TOKEN_NOT_SIGNED: {
    description: 'Token not signed',
    status: 500,
    code: 'TOKEN_NOT_SIGNED_ERROR',
    descriptionRu: 'Токен не подписан',
  },
  SEND_EMAIL: {
    description: 'Send email error',
    status: 500,
    code: 'SEND_EMAIL_ERROR',
    descriptionRu: 'Ошибка отправки электронной почты',
  },
  DECRYPTION: {
    description: 'Decryption error',
    status: 500,
    code: 'DECRYPTION_ERROR',
    descriptionRu: 'Ошибка расшифровки',
  },
  DB_NOTNULL_CONFLICT: {
    description: 'Not null conflict',
    status: 500,
    code: 'DB_NOTNULL_CONFLICT_ERROR',
    descriptionRu: 'Not-null конфликт',
  },
  DB: {
    description: 'Database error occurred',
    status: 500,
    code: 'DB_ERROR',
    descriptionRu: 'Произошла ошибка базы данных',
  },
  INTERNAL_SERVER_ERROR: {
    description: 'Internal Server Error',
    status: 500,
    code: 'INTERNAL_SERVER_ERROR_ERROR',
    descriptionRu: 'Внутренняя ошибка сервера',
  },
  NOT_IMPLEMENTED: {
    description: 'Not Implemented',
    status: 501,
    code: 'NOT_IMPLEMENTED_ERROR',
    descriptionRu: 'Сервер не поддерживает возможностей, необходимых для обработки запроса',
  },
  BAD_GATEWAY: {
    description: 'Bad Gateway',
    status: 502,
    code: 'BAD_GATEWAY_ERROR',
    descriptionRu: 'Неверный шлюз',
  },
  SERVICE_UNAVAILABLE: {
    description: 'Service Unavailable',
    status: 503,
    code: 'SERVICE_UNAVAILABLE_ERROR',
    descriptionRu: 'Сервис недоступен',
  },
  GATEWAY_TIMEOUT: {
    description: 'Gateway Timeout',
    status: 504,
    code: 'GATEWAY_TIMEOUT_ERROR',
    descriptionRu: 'Превышено время ожидания ответа',
  },
  HTTP_VERSION_NOT_SUPPORTED: {
    description: 'HTTP Version Not Supported',
    status: 505,
    code: 'HTTP_VERSION_NOT_SUPPORTED_ERROR',
    descriptionRu: 'Сервер не поддерживает или отказывается поддерживать указанную в запросе версию протокола HTTP',
  },
  VARIANT_ALSO_NEGOTIATES: {
    description: 'Variant Also Negotiates',
    status: 506,
    code: 'VARIANT_ALSO_NEGOTIATES_ERROR',
    descriptionRu: 'Выбранный вариант указывает сам на себя',
  },
  INSUFFICIENT_STORAGE: {
    description: 'Insufficient Storage',
    status: 507,
    code: 'INSUFFICIENT_STORAGE_ERROR',
    descriptionRu: 'Не хватает места для выполнения текущего запроса',
  },
  LOOP_DETECTED: {
    description: 'Loop Detected',
    status: 508,
    code: 'LOOP_DETECTED_ERROR',
    descriptionRu: 'Обнаружен бесконечный цикл',
  },
  UNASSIGNED: {
    description: 'Unassigned',
    status: 509,
    code: 'UNASSIGNED_ERROR',
    descriptionRu: 'Не назначен',
  },
  NOT_EXTENDED: {
    description: 'Not Extended',
    status: 510,
    code: 'NOT_EXTENDED_ERROR',
    descriptionRu: 'Не продлен',
  },
  NETWORK_AUTHENTICATION_REQUIRED: {
    description: 'Network Authentication Required',
    status: 511,
    code: 'NETWORK_AUTHENTICATION_REQUIRED_ERROR',
    descriptionRu: 'Требуется сетевая аутентификация',
  },
  IS_BUSY: {
    description: 'This time is busy',
    status: 400,
    code: 'IS_BUSY_ERROR',
    descriptionRu: 'Это время занято',
  },
  NO_APPOINTMENTS_ON_THIS_DATE: {
    description: 'No appointments on this date',
    status: 400,
    code: 'NO_APPOINTMENTS_ON_THIS_DATE',
    descriptionRu: 'Нет встреч на эту дату',
  },
  HAS_SECOND_USER: {
    description: 'Has second users by account',
    status: 400,
    code: 'HAS_SECOND_USER_ERROR',
    descriptionRu: 'Учетная запись имеет вторичных пользователей',
  },
  PHOTO_NOT_UPLOAD: {
    description: 'Photo not upload',
    status: 500,
    code: 'PHOTO_NOT_UPLOAD',
    descriptionRu: 'Фото не загружено',
  },
  POLL_IS_EXPIRED: {
    description: 'Poll is expired',
    status: 400,
    code: 'POLL_IS_EXPIRED',
    descriptionRu: 'Срок действия опроса истек',
  },
  ALREADY_VOTED: {
    description: 'You have already voted',
    status: 400,
    code: 'ALREADY_VOTED',
    descriptionRu: 'Вы уже проголосовали',
  },
  EDS_REQ_NOT_PAYABLE: {
    description: 'Not payable',
    status: 400,
    code: 'EDS_REQ_NOT_PAYABLE',
    descriptionRu: 'Недоступно для оплаты онлайн',
  },
  EDS_REQ_POINTS_LIMIT: {
    description: 'Points amount exceeds the limit',
    status: 400,
    code: 'EDS_REQ_POINTS_LIMIT',
    descriptionRu: 'Количество бонусов превышает доступный лимит списания',
  },
  ALREADY_RESPONDED: {
    description: 'You have already responded',
    status: 400,
    code: 'ALREADY_RESPONDED',
    descriptionRu: 'Вы уже сделали отклик на текущую вакансию',
  },
};
