module.exports = {
  SECRET_ACCESS: 'access',
  EXPIRE_ACCESS: '1h',
  ALGORITHM_ACCESS: 'HS256',

  SECRET_REFRESH: 'refresh',
  EXPIRE_REFRESH: '30d',
  ALGORITHM_REFRESH: 'HS512',

  SECRET_RESTORE: 'restore',
  EXPIRE_RESTORE: '1d',
  ALGORITHM_RESTORE: 'HS512',

  EXPIRE_CONFIRMED: '30m',
  ALPHABET_CONFIRMED: '0123456789',
  TOKEN_LENGTH_CONFIRMED: 5,

  HTTP_API_PREFIX: 'api',
  HTTP_API_PORT: '3000',
  HTTP_PUBLIC_URL: 'localhost',
  HTTP_UI_OPENAPI_PREFIX: 'documentation',
  HTTP_UI_OPENAPI_PUBLIC_URL: 'http://localhost',

  DB_DIALECT: 'postgres',

  FILE_TEMP_DIR: 'cache',
};
