/* eslint-disable max-len */
const parseDuration = require('parse-duration');
const path = require('path');
const constants = require('./constants');

require('dotenv').config({ path: path.join(__dirname, '../../../', '.env') });

const SECRET_ACCESS = process.env.SECRET_ACCESS || constants.SECRET_ACCESS;
const EXPIRE_ACCESS = parseDuration(process.env.EXPIRE_ACCESS || constants.EXPIRE_ACCESS);
const ALGORITHM_ACCESS = process.env.ALGORITHM_ACCESS || constants.ALGORITHM_ACCESS;

const SECRET_REFRESH = process.env.SECRET_REFRESH || constants.SECRET_REFRESH;
const EXPIRE_REFRESH = parseDuration(process.env.EXPIRE_REFRESH || constants.EXPIRE_REFRESH);

const ALGORITHM_REFRESH = process.env.ALGORITHM_REFRESH || constants.ALGORITHM_REFRESH;

const SECRET_RESTORE = process.env.SECRET_RESTORE || constants.SECRET_RESTORE;
const EXPIRE_RESTORE = parseDuration(process.env.EXPIRE_RESTORE || constants.EXPIRE_RESTORE);
const ALGORITHM_RESTORE = process.env.ALGORITHM_ACCESS || constants.ALGORITHM_RESTORE;

const EXPIRE_CONFIRMED = parseDuration(process.env.EXPIRE_CONFIRMED || constants.EXPIRE_CONFIRMED);
const ALPHABET_CONFIRMED = process.env.ALPHABET_CONFIRMED || constants.ALPHABET_CONFIRMED;
const TOKEN_LENGTH_CONFIRMED = parseInt(process.env.TOKEN_LENGTH_CONFIRMED || constants.TOKEN_LENGTH_CONFIRMED, 10);

const HTTP_API_PREFIX = process.env.HTTP_API_PREFIX || constants.HTTP_API_PREFIX;
const HTTP_API_PORT = process.env.HTTP_API_PORT || constants.HTTP_API_PORT;
const HTTP_PUBLIC_URL = process.env.HTTP_PUBLIC_URL || constants.HTTP_PUBLIC_URL;
const HTTP_UI_OPENAPI_PREFIX = process.env.HTTP_UI_OPENAPI_PREFIX || constants.HTTP_UI_OPENAPI_PREFIX;
const HTTP_UI_OPENAPI_PUBLIC_URL = process.env.HTTP_UI_OPENAPI_PUBLIC_URL || constants.HTTP_UI_OPENAPI_PUBLIC_URL;

const DB_PASSWORD = process.env.DB_PASSWORD || constants.DB_PASSWORD;
const DB_USERNAME = process.env.DB_USERNAME || constants.DB_USERNAME;
const DB_DATABASE = process.env.DB_DATABASE || constants.DB_DATABASE;
const DB_DIALECT = process.env.DB_DIALECT || constants.DB_DIALECT;
const DB_HOST = process.env.DB_HOST || constants.DB_HOST;

const SMS_EXT_LOGIN = process.env.SMS_EXT_LOGIN || constants.SMS_EXT_LOGIN;
const SMS_EXT_PASSWORD = process.env.SMS_EXT_PASSWORD || constants.SMS_EXT_PASSWORD;
const SMS_EXT_PUBLIC_URL = process.env.SMS_EXT_PUBLIC_URL || constants.SMS_EXT_PUBLIC_URL;
const SMS_EXT_SENDER = process.env.SMS_EXT_SENDER || constants.SMS_EXT_SENDER;

const EMAIL_EXT_LOGIN = process.env.EMAIL_EXT_LOGIN || constants.EMAIL_EXT_LOGIN;
const EMAIL_EXT_PASSWORD = process.env.EMAIL_EXT_PASSWORD || constants.EMAIL_EXT_PASSWORD;
const EMAIL_EXT_PUBLIC_URL = process.env.EMAIL_EXT_PUBLIC_URL || constants.EMAIL_EXT_PUBLIC_URL;
const EMAIL_EXT_SENDER = process.env.EMAIL_EXT_SENDER || constants.EMAIL_EXT_SENDER;

const DADATA_EXT_TOKEN = process.env.DADATA_EXT_TOKEN || constants.DADATA_EXT_TOKEN;
const DADATA_EXT_SECRET = process.env.DADATA_EXT_SECRET || constants.DADATA_EXT_SECRET;
const DADATA_CLEANER_EXT_PUBLIC_URL = process.env.DADATA_CLEANER_EXT_PUBLIC_URL || constants.DADATA_CLEANER_EXT_PUBLIC_URL;
const DADATA_SUGGESTIONS_EXT_PUBLIC_URL = process.env.DADATA_SUGGESTIONS_EXT_PUBLIC_URL || constants.DADATA_SUGGESTIONS_EXT_PUBLIC_URL;

const MANAGING_EXT_TOKEN = process.env.MANAGING_EXT_TOKEN || constants.MANAGING_EXT_TOKEN;
const MANAGING_EXT_PUBLIC_URL = process.env.MANAGING_EXT_PUBLIC_URL || constants.MANAGING_EXT_PUBLIC_URL;

const NEDOLZHNIK_EXT_TOKEN = process.env.NEDOLZHNIK_EXT_TOKEN || constants.NEDOLZHNIK_EXT_TOKEN;
const NEDOLZHNIK_EXT_PUBLIC_URL = process.env.NEDOLZHNIK_EXT_PUBLIC_URL || constants.NEDOLZHNIK_EXT_PUBLIC_URL;

const CITIES_EXT_PUBLIC_URL = process.env.CITIES_EXT_PUBLIC_URL || constants.CITIES_EXT_PUBLIC_URL;

const API_KEYS = process.env.API_KEYS.split(',').map((item) => item.trim());

const { FIREBASE_ACC_TYPE } = process.env;
const { FIREBASE_PROJECT_ID } = process.env;
const { FIREBASE_PRIVATE_KEY_ID } = process.env;
const { FIREBASE_PRIVATE_KEY } = process.env;
const { FIREBASE_CLIENT_EMAIL } = process.env;
const { FIREBASE_CLIENT_ID } = process.env;
const { FIREBASE_AUTH_URI } = process.env;
const { FIREBASE_TOKEN_URI } = process.env;
const { FIREBASE_AUTH_PROVIDER } = process.env;
const { FIREBASE_CLIENT_X509 } = process.env;

const UPP_ORN_EXT_LOGIN = process.env.UPP_ORN_EXT_LOGIN || constants.UPP_ORN_EXT_LOGIN;
const UPP_ORN_EXT_PASSWORD = process.env.UPP_ORN_EXT_PASSWORD || constants.UPP_ORN_EXT_PASSWORD;
const UPP_ORN_EXT_PUBLIC_URL = process.env.UPP_ORN_EXT_PUBLIC_URL || constants.UPP_ORN_EXT_PUBLIC_URL;

const S3_ACCESS_KEY_ID = process.env.S3_ACCESS_KEY_ID || constants.S3_ACCESS_KEY_ID;
const S3_SECRET_ACCESS_KEY = process.env.S3_SECRET_ACCESS_KEY || constants.S3_SECRET_ACCESS_KEY;
const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME || constants.S3_BUCKET_NAME;

const CMS_EXT_PUBLIC_URL = process.env.CMS_EXT_PUBLIC_URL || constants.CMS_EXT_PUBLIC_URL;
const CMS_EXT_TOKEN = process.env.CMS_EXT_TOKEN || constants.CMS_EXT_TOKEN;

const SESSION_COOKIE_NAME = process.env.SESSION_COOKIE_NAME || constants.SESSION_COOKIE_NAME;
const SESSION_SECRET = process.env.SESSION_SECRET || constants.SESSION_SECRET;
const SESSION_COOKIE_SECURE = (process.env.SESSION_COOKIE_SECURE || constants.SESSION_COOKIE_SECURE || 'false') !== 'false';

const EDS_EXT_PUBLIC_URL = process.env.EDS_EXT_PUBLIC_URL || constants.EDS_EXT_PUBLIC_URL;
const EDS_EXT_TOKEN = process.env.EDS_EXT_TOKEN || constants.EDS_EXT_TOKEN;

const EDS_SERVICES_EXT_PUBLIC_URL = process.env.EDS_SERVICES_EXT_PUBLIC_URL || constants.EDS_SERVICES_EXT_PUBLIC_URL;
const EDS_SERVICES_EXT_TOKEN = process.env.EDS_SERVICES_EXT_TOKEN || constants.EDS_SERVICES_EXT_TOKEN;

const GIS_ZHKH_WSDL_URL = process.env.GIS_ZHKH_WSDL_URL || constants.GIS_ZHKH_WSDL_URL;

const INDICATION_REPORT_EMAIL = process.env.INDICATION_REPORT_EMAIL || constants.INDICATION_REPORT_EMAIL;
const INDICATION_REPORT_CRON_EXP = process.env.INDICATION_REPORT_CRON_EXP || constants.INDICATION_REPORT_CRON_EXP;

const FILE_TEMP_DIR = process.env.FILE_TEMP_DIR || constants.FILE_TEMP_DIR;

const NEWS_REPORT_CRON_EXP = process.env.NEWS_REPORT_CRON_EXP || constants.NEWS_REPORT_CRON_EXP;
const REGISTRATION_REQUEST_CLEAR_CACHE_CRON_EXP = process.env.REGISTRATION_REQUEST_CLEAR_CACHE_CRON_EXP || constants.REGISTRATION_REQUEST_CLEAR_CACHE_CRON_EXP;
const LOYALTY_INVITATION_CLEAR_CACHE_CRON_EXP = process.env.LOYALTY_INVITATION_CLEAR_CACHE_CRON_EXP || constants.LOYALTY_INVITATION_CLEAR_CACHE_CRON_EXP;
const LOYALTY_OPERATION_CLEAR_CACHE_CRON_EXP = process.env.LOYALTY_OPERATION_CLEAR_CACHE_CRON_EXP || constants.LOYALTY_OPERATION_CLEAR_CACHE_CRON_EXP;

module.exports = {
  SECRET_ACCESS,
  EXPIRE_ACCESS,
  ALGORITHM_ACCESS,

  SECRET_REFRESH,
  EXPIRE_REFRESH,
  ALGORITHM_REFRESH,

  SECRET_RESTORE,
  EXPIRE_RESTORE,
  ALGORITHM_RESTORE,

  EXPIRE_CONFIRMED,
  ALPHABET_CONFIRMED,
  TOKEN_LENGTH_CONFIRMED,

  HTTP_API_PREFIX,
  HTTP_API_PORT,
  HTTP_PUBLIC_URL,

  HTTP_UI_OPENAPI_PREFIX,
  HTTP_UI_OPENAPI_PUBLIC_URL,

  DB_DIALECT,
  DB_HOST,
  DB_PASSWORD,
  DB_USERNAME,
  DB_DATABASE,

  SMS_EXT_LOGIN,
  SMS_EXT_PASSWORD,
  SMS_EXT_PUBLIC_URL,
  SMS_EXT_SENDER,

  EMAIL_EXT_LOGIN,
  EMAIL_EXT_PASSWORD,
  EMAIL_EXT_PUBLIC_URL,
  EMAIL_EXT_SENDER,

  DADATA_EXT_TOKEN,
  DADATA_EXT_SECRET,
  DADATA_CLEANER_EXT_PUBLIC_URL,
  DADATA_SUGGESTIONS_EXT_PUBLIC_URL,

  MANAGING_EXT_TOKEN,
  MANAGING_EXT_PUBLIC_URL,

  NEDOLZHNIK_EXT_TOKEN,
  NEDOLZHNIK_EXT_PUBLIC_URL,

  CITIES_EXT_PUBLIC_URL,
  API_KEYS,

  FIREBASE_ACC_TYPE,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_PROVIDER,
  FIREBASE_CLIENT_X509,

  UPP_ORN_EXT_LOGIN,
  UPP_ORN_EXT_PASSWORD,
  UPP_ORN_EXT_PUBLIC_URL,

  S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY,
  S3_BUCKET_NAME,

  CMS_EXT_PUBLIC_URL,
  CMS_EXT_TOKEN,

  SESSION_COOKIE_NAME,
  SESSION_SECRET,
  SESSION_COOKIE_SECURE,

  EDS_EXT_PUBLIC_URL,
  EDS_EXT_TOKEN,

  EDS_SERVICES_EXT_PUBLIC_URL,
  EDS_SERVICES_EXT_TOKEN,

  GIS_ZHKH_WSDL_URL,

  INDICATION_REPORT_EMAIL,
  INDICATION_REPORT_CRON_EXP,

  FILE_TEMP_DIR,

  NEWS_REPORT_CRON_EXP,
  REGISTRATION_REQUEST_CLEAR_CACHE_CRON_EXP,
  LOYALTY_INVITATION_CLEAR_CACHE_CRON_EXP,
  LOYALTY_OPERATION_CLEAR_CACHE_CRON_EXP,
};
